app = "neonpop-art"
primary_region = "fra"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[mounts]
  source = "shopify_data"
  destination = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    path = "/"
