api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "checkout-free-shipping"
type = "function"
uid = "302f65be-bd58-92ed-03ed-ed211b1028a696546a12"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
